object Libs {
    const val coreKtx = "androidx.core:core-ktx:${Version.coreKtx}"
    const val googleAndroidMaterial = "com.google.android.material:material:${Version.googleAndroidMaterial}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Version.constraintLayout}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${Version.hilt}"
    const val hiltCompiler = "com.google.dagger:hilt-android-compiler:${Version.hilt}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Version.retrofit}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Version.okhttp}"
    const val loggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Version.okhttp}"
    const val moshi = "com.squareup.moshi:moshi:${Version.moshi}"
    const val moshiKotlin = "com.squareup.moshi:moshi-kotlin:${Version.moshi}"
    const val moshiKotlinCodegen = "com.squareup.moshi:moshi-kotlin-codegen:${Version.moshi}"
    const val moshiConverterRetrofit = "com.squareup.retrofit2:converter-moshi:${Version.moshiConverterRetrofit}"
    const val kotlinCoroutineAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Version.kotlinCoroutineAndroid}"
    const val kotlinCoroutineCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Version.kotlinCoroutineAndroid}"
    const val lifecycleExtensions = "android.arch.lifecycle:extensions:${Version.lifecycleExtensions}"
    const val lifecycleViewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.lifecycleViewModelKtx}"
    const val lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Version.lifecycleRuntimeKtx}"
    const val activityKtx = "androidx.activity:activity-ktx:${Version.activityKtx}"
    const val glide = "com.github.bumptech.glide:glide:${Version.glide}"
    const val timber = "com.jakewharton.timber:timber:${Version.timber}"
}