object Version {
    const val coreKtx = "1.7.0"
    const val googleAndroidMaterial = "1.4.0"
    const val gradleBuildTools = "7.0.4"
    const val kotlinPlugin = "1.7.10"
    const val constraintLayout = "2.1.4"
    const val hilt = "2.42"
    const val retrofit = "2.9.0"
    const val okhttp = "4.10.0"
    const val moshi = "1.13.0"
    const val moshiConverterRetrofit = "2.9.0"
    const val secretGradlePlugin = "2.0.1"
    const val kotlinCoroutineAndroid = "1.6.4"
    const val lifecycleExtensions = "1.1.1"
    const val lifecycleViewModelKtx = "2.6.0-alpha01"
    const val lifecycleRuntimeKtx = "2.3.1"
    const val activityKtx = "1.4.0"
    const val glide = "4.13.2"
    const val timber = "4.7.1"
}